# Generated by Django 4.2.6 on 2023-10-15 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="vendor_id",
            new_name="vendor",
        ),
        migrations.RenameField(
            model_name="trasactions",
            old_name="product_id",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="trasactions",
            old_name="vendor_id",
            new_name="vendor",
        ),
    ]
